version: "3.9"
services:
  app:
    build: .
    container_name: dockchat_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/dockchat
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: dockchat_mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
